function GenerichumanncbiIdsnoParents = importGEMMAfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GENERICHUMANNCBIIDSNOPARENTS = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  GENERICHUMANNCBIIDSNOPARENTS = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  GenerichumanncbiIdsnoParents = importfile("/Users/aurinaa/Google_drive/PostDoc/projects/GeneticBrainHubs/data/enrichment/Generic_human_ncbiIds_noParents.an.txt", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Sep-2020 12:04:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ProbeName", "GeneSymbols", "GeneNames", "GOTerms", "GemmaIDs", "NCBIids"];
opts.VariableTypes = ["double", "string", "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["GeneSymbols", "GeneNames", "GOTerms"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["GeneSymbols", "GeneNames", "GOTerms"], "EmptyFieldRule", "auto");

% Import the data
GenerichumanncbiIdsnoParents = readtable(filename, opts);

end