function pecgenes1 = importpec_genes(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PECGENES1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  PECGENES1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  pecgenes1 = importfile("/Users/aurinaa/Google_drive/PostDoc/projects/GeneticBrainHubs/data/reeqtls/pec_genes.annot_FINAL.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Sep-2020 12:02:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "ENSG00000228463rs13376597rs11260563";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "ENSG00000228463rs13376597rs11260563", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "ENSG00000228463rs13376597rs11260563", "EmptyFieldRule", "auto");

% Import the data
pecgenes1 = readmatrix(filename, opts);

end