function pecadhd = importEMAGMApec(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PECADHD = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  PECADHD = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  pecadhd = importfile("/Users/aurinaa/Google_drive/Genetics_connectome/HumanHubs_figures/data/emagma_results/emagma_pec/pec_adhd.genes.out.annot.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-May-2020 14:47:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["GENE", "CHR", "START", "STOP", "NSNPS", "NPARAM", "N", "ZSTAT", "P", "ENTREZID", "SYMBOL", "GENENAME"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["GENE", "SYMBOL", "GENENAME"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["GENE", "SYMBOL", "GENENAME"], "EmptyFieldRule", "auto");

% Import the data
pecadhd = readtable(filename, opts);

end