function HARgeneIDs = importHARgeneIDs(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GPROFILERHSAPIENS18062020112226 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  GPROFILERHSAPIENS18062020112226 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  gProfilerhsapiens18062020112226 = importfile("/Users/aurinaa/Google_drive/PostDoc/projects/GeneticBrainHubs/data/HARgenes/gProfiler_hsapiens_18-06-2020_11-22-26.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Jun-2020 11:26:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["initial_alias", "converted_alias", "name", "description", "namespace"];
opts.VariableTypes = ["string", "double", "string", "string", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["initial_alias", "name", "description"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["initial_alias", "name", "description", "namespace"], "EmptyFieldRule", "auto");

% Import the data
HARgeneIDs = readtable(filename, opts);

end