function degHCPLRCnew22 = importREGINFOfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DEGHCPLRCNEW22 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DEGHCPLRCNEW22 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  degHCPLRCnew22 = importfile("/Users/aurinaa/Google_drive/Genetics_connectome/HumanHubs_figures/HumanHubs_manuscript/degHCP_LRCnew2_2.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Mar-2020 13:02:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["degree", "ycoord", "number", "avcoord", "numberRev", "section", "ycoordROT2use", "HEM", "degFlip", "sectionOrig"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "sectionOrig", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "sectionOrig", "EmptyFieldRule", "auto");

% Import the data
degHCPLRCnew22 = readtable(filename, opts);

end