function HCPpsychENCODEannotated = importPSYCHfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HCPPSYCHENCODEANNOTATED = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  HCPPSYCHENCODEANNOTATED = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  HCPpsychENCODEannotated = importfile("/Users/aurinaa/Google_drive/Genetics_connectome/HumanHubs_figures/data/reeqtls/HCP_psychENCODE_annotated.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-May-2020 12:15:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["gene_id_stub", "gene_id", "gene_chr", "gene_start", "gene_end", "strand", "number_of_SNPs_tested", "SNP_distance_to_TSS", "SNP_id", "SNP_chr", "SNP_start", "SNP_end", "nominal_pval", "regression_slope", "top_SNP", "FDR", "converted_alias", "name", "description", "namespace"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "categorical", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "SNP_id", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["strand", "SNP_id", "name", "description", "namespace"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["gene_id_stub", "gene_id", "gene_chr", "SNP_chr", "converted_alias"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["gene_id_stub", "gene_id", "gene_chr", "SNP_chr", "converted_alias"], "ThousandsSeparator", ",");

% Import the data
HCPpsychENCODEannotated = readtable(filename, opts);

end