function GenerefGene = importHARgenes(filename)%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Aurina/GoogleDrive/Genetics_connectome/HumanExpression/data/HARgenes/1-s2.0-S0092867416311692-mmc2.xlsx
%    Worksheet: Table S1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/08/20 11:19:51

%% Import the data
[~, ~, raw] = xlsread(filename,'Table S1');
raw = raw(:,5);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);

%% Allocate imported array to column variable names
GenerefGene = cellVectors(:,1);

%% Clear temporary variables
clearvars raw cellVectors;
end