function annotGenes = importEQTLfile(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   HCPPSYCHENCODEANNOTATED = IMPORTFILE1(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   HCPPSYCHENCODEANNOTATED = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   HCPpsychENCODEannotated = importfile1('HCP_psychENCODE_annotated.txt', 2, 2115);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/12/09 11:52:05

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: text (%s)
%   column7: double (%f)
%	column8: double (%f)
%   column9: text (%s)
%	column10: text (%s)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: text (%s)
%	column18: text (%s)
%   column19: text (%s)
%	column20: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%f%f%s%f%f%s%s%f%f%f%f%f%f%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
annotGenes = table(dataArray{1:end-1}, 'VariableNames', {'gene_id_stub','gene_id','gene_chr','gene_start','gene_end','strand','number_of_SNPs_tested','SNP_distance_to_TSS','SNP_id','SNP_chr','SNP_start','SNP_end','nominal_pval','regression_slope','top_SNP','FDR','converted_alias','name','description','namespace'});

