function gProfilerHCPresults = importORAfile(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   GPROFILERHCPRESULTS = IMPORTFILE1(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   GPROFILERHCPRESULTS = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   gProfilerHCPresults = importfile1('gProfiler_HCP_results.csv', 2, 6);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/12/11 10:53:25

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[4,5,6,7,8,9]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [4,5,6,7,8,9]);
rawCellColumns = raw(:, [1,2,3,10]);


%% Create output variable
gProfilerHCPresults = table;
gProfilerHCPresults.source = rawCellColumns(:, 1);
gProfilerHCPresults.term_name = rawCellColumns(:, 2);
gProfilerHCPresults.term_id = rawCellColumns(:, 3);
gProfilerHCPresults.adjusted_p_value = cell2mat(rawNumericColumns(:, 1));
gProfilerHCPresults.negative_log10_of_adjusted_p_value = cell2mat(rawNumericColumns(:, 2));
gProfilerHCPresults.term_size = cell2mat(rawNumericColumns(:, 3));
gProfilerHCPresults.query_size = cell2mat(rawNumericColumns(:, 4));
gProfilerHCPresults.intersection_size = cell2mat(rawNumericColumns(:, 5));
gProfilerHCPresults.effective_domain_size = cell2mat(rawNumericColumns(:, 6));
gProfilerHCPresults.intersections = rawCellColumns(:, 4);

