function T = importHARgenes(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  HARGENES = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  HARGENES = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  HARGENES = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  HARgenes = importfile("/Users/aurinaa/Google_drive/PostDoc/projects/GeneticBrainHubs/data/emagma_results/HAR_genes.xlsx", "Table S1", [2, 2738]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Jun-2020 10:27:44

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 2738];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":I" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Chr", "Start", "End", "FuncrefGene", "GenerefGene", "HAR", "HAR1", "ChromHMMEpigenomicsRoadmap", "InteractinggenesGohetal2012Jinetal2013Lietal2010Lietal2012Maeta"];
opts.VariableTypes = ["categorical", "double", "double", "categorical", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["GenerefGene", "HAR", "HAR1", "ChromHMMEpigenomicsRoadmap", "InteractinggenesGohetal2012Jinetal2013Lietal2010Lietal2012Maeta"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Chr", "FuncrefGene", "GenerefGene", "HAR", "HAR1", "ChromHMMEpigenomicsRoadmap", "InteractinggenesGohetal2012Jinetal2013Lietal2010Lietal2012Maeta"], "EmptyFieldRule", "auto");

% Import the data
HARgenes = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":I" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    HARgenes = [HARgenes; tb]; %#ok<AGROW>
end
% Loop over the list and get the unique gene names
listALL = {}; 
k=1; 
for g=1:size(HARgenes,1)
    % split each cell
    newStr = split(HARgenes.GenerefGene{g}, ','); 
    listALL(k:k+length(newStr)-1) = newStr; 
    k=k+length(newStr); 
end
T = table; 
T.genes = unique(listALL'); 
end